---
require: rubocop-rspec

AllCops:
  Exclude:
    - 'attributes/*'
    - 'recipes/*'

Lint/AmbiguousOperator:
  Enabled: false

Lint/AmbiguousRegexpLiteral:
  Enabled: false

Metrics/ModuleLength:
  Exclude:
    - 'spec/**/*'

Style/AndOr:
  Enabled: false

Style/Not:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false

Style/ClassVars:
  Enabled: false

Style/Documentation:
  Exclude:
    - 'libraries/chef_resource*'
    - 'spec/**/*'

Style/EmptyLiteral:
  Enabled: false

Style/MethodDefParentheses:
  EnforcedStyle: require_no_parentheses

Style/PercentLiteralDelimiters:
  Enabled: false

Style/RegexpLiteral:
  EnforcedStyle: percent_r

Style/SpaceInsideHashLiteralBraces:
  Enabled: false
